#!/usr/bin/env bash
# Script: 0-transfer_file
# Description: Transfers a file from the client to a server using scp
#
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# Parameters:
#   - PATH_TO_FILE: Path to the file to be transferred
#   - IP: IP address of the server to transfer the file to
#   - USERNAME: Username scp connects with on the server
#   - PATH_TO_SSH_KEY: Path to the SSH private key that scp uses
#
# If less than 4 parameters are passed, display usage instructions
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Transfer the file to the server with strict host key checking disabled
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
