#!/usr/bin/env bash

# Script: duplicate_web_server.sh
# Description: Duplicates web-01 to web-02
# Author: Dennis Makaka
# Date: March 31, 2024

# Uncomment the line below to enable script debugging
# set -x

echo -e "Updating and performing minor checks...\n"

# Function to check and install a package if not already installed
function install() {
    command -v "$1" &> /dev/null

    # Check if the package is installed
    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

# Install Nginx
install nginx

echo -e "\nSetting up some minor configurations.\n"

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Set user ownership and permissions for website files
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create directories if they do not exist
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create a new index file
echo "Hello World!" > /var/www/html/index.html

# Create a custom error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup the default server configuration file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Define the new server configuration
server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}"

# Apply the new server configuration
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Start or restart the Nginx service based on its status
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi

